// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ZfghR68Nx0gMnsiH2huFBPk-0Nd0da8',
    appId: '1:437433110122:web:cd80e5cd4dcb6df0da8413',
    messagingSenderId: '437433110122',
    projectId: 'shopatoz-a8bb8',
    authDomain: 'shopatoz-a8bb8.firebaseapp.com',
    storageBucket: 'shopatoz-a8bb8.appspot.com',
    measurementId: 'G-5D10JNJCCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnQS1oJoedx1zVtidN4-FQZHbJ-hmhgq0',
    appId: '1:437433110122:android:30e810aef1f63c53da8413',
    messagingSenderId: '437433110122',
    projectId: 'shopatoz-a8bb8',
    storageBucket: 'shopatoz-a8bb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1iVmtizPJIPirPIHLn38oiQUQVPVwrqQ',
    appId: '1:437433110122:ios:1f1956577d63ba5fda8413',
    messagingSenderId: '437433110122',
    projectId: 'shopatoz-a8bb8',
    storageBucket: 'shopatoz-a8bb8.appspot.com',
    iosBundleId: 'com.example.firebaseUserAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1iVmtizPJIPirPIHLn38oiQUQVPVwrqQ',
    appId: '1:437433110122:ios:0edce32f36a561b3da8413',
    messagingSenderId: '437433110122',
    projectId: 'shopatoz-a8bb8',
    storageBucket: 'shopatoz-a8bb8.appspot.com',
    iosBundleId: 'com.example.firebaseUserAppFlutter.RunnerTests',
  );
}
